name: 学术文献
description: 此目录包含关于跨性别议题的学术文献，包括人文、医学、法律和社会科学领域的研究和资料，包括但不限于发表于学术期刊的论文和由大学附属出版社出版的学术书籍。采用近似于学术写作的风格创作、发布于某些期刊杂志，但不确定是否为「学术」文献的，放置于「杂志及新闻报道」分类。
curator: ''
source: ''
tags:
- 跨性别
- 学术文献
- 人文
- 医学
- 法律
- 社会科学
license: ''
files:
- name: 2023_多元性别与媒体再现
  filename: 2023_多元性别与媒体再现.pdf
  type: document
  format: PDF Document
  size: 4514
  md5: e94162284dd1358d987ada6abc7444de
  page: 2023_多元性别与媒体再现_page.md
- name: GALE精选图书目录_2023-2024
  filename: GALE精选图书目录_2023-2024.pdf
  type: document
  format: PDF Document
  size: 4517425
  md5: 026edddc2b4ffecff7d30199b3909238
  page: GALE精选图书目录_2023-2024_page.md
- name: 关于现代汉语中‘族’与‘党’的演变研究_索非亚·巴雷托_2016
  filename: 关于现代汉语中‘族’与‘党’的演变研究_索非亚·巴雷托_2016.pdf
  type: document
  format: PDF Document
  size: 3690508
  md5: bbf612e06862b19aa27474167f6e261a
  page: 关于现代汉语中‘族’与‘党’的演变研究_索非亚·巴雷托_2016_page.md
subdirs:
- 人文社科
- 医学
- 法律
