name: 文学作品和艺术创作
description: 本部分收录一切形式的跨儿文学艺术创作。无论是发布于互联网某个阴暗角落的「变性人」自传，还是形式晦涩、发人深省的诗歌电影，均可收录在本版块。，涵盖了多种形式的表达，包括小说、漫画、纪实作品、自传和诗歌等。
curator: ''
source: ''
tags:
- 跨性别
- 文学作品
- 艺术创作
- 自传
- 小说
- 漫画
- 纪实作品
- 诗歌
license: ''
files:
- name: 2024年威尼斯双年展素人艺术家展评
  filename: 2024年威尼斯双年展素人艺术家展评.pdf
  type: document
  format: PDF Document
  size: 817604
  md5: a917c0611a68126b806cc1f41fe83ab6
  page: 2024年威尼斯双年展素人艺术家展评_page.md
- name: 吴曾_镜头切开身份_艺术创作与酷儿文化
  filename: 吴曾_镜头切开身份_艺术创作与酷儿文化.pdf
  type: document
  format: PDF Document
  size: 740565
  md5: 916560cc15b3e25646a104869fdf351c
  page: 吴曾_镜头切开身份_艺术创作与酷儿文化_page.md
- name: 多元性别与艺术界动态
  filename: 多元性别与艺术界动态.pdf
  type: document
  format: PDF Document
  size: 9119114
  md5: 0880adc239f6214909692e74548af1fc
  page: 多元性别与艺术界动态_page.md
- name: 巴特勒作品集
  filename: 巴特勒作品集.pdf
  type: document
  format: PDF Document
  size: 6957144
  md5: ee4c6ce5299761688ff36b76b19b855e
  page: 巴特勒作品集_page.md
- name: 布林客007-偶像与情感-2015
  filename: 布林客007-偶像与情感-2015.pdf
  type: document
  format: PDF Document
  size: 6335361
  md5: e1b6620cb837707eb11ccf713853fad9
  page: 布林客007-偶像与情感-2015_page.md
- name: 海伦·马尔滕与亚力汉德罗·西塞科_艺术创作与社会介入_2011
  filename: 海伦·马尔滕与亚力汉德罗·西塞科_艺术创作与社会介入_2011.pdf
  type: document
  format: PDF Document
  size: 1468212
  md5: 3e8ad1f38764d1f21715adbf37193260
  page: 海伦·马尔滕与亚力汉德罗·西塞科_艺术创作与社会介入_2011_page.md
- name: 白蛇主题的多维视角研究_罗靓_现代华文文学
  filename: 白蛇主题的多维视角研究_罗靓_现代华文文学.pdf
  type: document
  format: PDF Document
  size: 1933768
  md5: b5901b71e27dedf6ee680615892dd698
  page: 白蛇主题的多维视角研究_罗靓_现代华文文学_page.md
- name: 艺术家就业计划指引_2022_Creatives_Rebuild_New_York
  filename: 艺术家就业计划指引_2022_Creatives_Rebuild_New_York.pdf
  type: document
  format: PDF Document
  size: 962343
  md5: 138abc3e7e4144cbc2695fbb2238a7e0
  page: 艺术家就业计划指引_2022_Creatives_Rebuild_New_York_page.md
- name: 艾萨克朱利安：新的未来与酷儿往事
  filename: 艾萨克朱利安：新的未来与酷儿往事.pdf
  type: document
  format: PDF Document
  size: 2640939
  md5: 9fdbe417c32d69b09f84914c26f011c1
  page: 艾萨克朱利安：新的未来与酷儿往事_page.md
subdirs:
- 图像
- 小说
- 纪实作品
- 自传
- 诗歌
- 音频影像
