name: 荡妇学院
description: 本目录包含了《荡妇学院》的教程和训练资料，这是一个专注于性别认同与性体验的社群项目。该项目以教育为核心，致力于提供跨性别人士所需的知识与技能，帮助他们在性别表达和生活方式上更具自信和自由。《荡妇学院》不仅涉及跨性别人士的心理适应和生活指导，还涵盖了对身体的认知、社交技巧的提升以及与他人的互动。通过分享生活体验与策略，该资料旨在打破社会对性别认同的偏见，建立一个更为包容的环境。
curator: ''
source: ''
tags:
- 跨性别
- 性别认同
- 生活体验
- 教育
- 社群支持
- 心理适应
- 社交技巧
license: ''
files:
- name: 荡妇学院
  filename: 荡妇学院.jpg
  type: image
  format: JPEG Image
  size: 7984467
  md5: 3c18ae07851756f2fc5c48ad371bbf3f
  page: 荡妇学院.jpg
subdirs: []
